server:
  port: 8080
spring:
#模板
  freemarker:
    cache: false
    charset: utf-8
    check-template-location: true
    expose-request-attributes: true
    content-type: text/html
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    #设定文件路径
    template-loader-path: classpath:/templates/

